<a href="https://colab.research.google.com/github/gowravmannem/Aromatase-Drug-Discovery/blob/main/aromatase_project_part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Installing Libraries

In [ ]:
# importing Chembl Database
! pip install chembl_webresource_client

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: chembl_webresource_client in /usr/local/lib/python3.7/dist-packages (0.10.8)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.7/dist-packages (from chembl_webresource_client) (1.24.3)
Requirement already satisfied: easydict in /usr/local/lib/python3.7/dist-packages (from chembl_webresource_client) (1.9)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.7/dist-packages (from chembl_webresource_client) (2.23.0)
Requirement already satisfied: requests-cache~=0.7.0 in /usr/local/lib/python3.7/dist-packages (from chembl_webresource_client) (0.7.5)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2022.6.15)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.0.4)
Requirement already satisfied: pyyaml>=5.4 in /usr/local/lib/python3.7/dist-packages (from requests-cache~=0.7.0->chembl_webresource_client) (6.0)
Requirement already satisfied: attrs<22.0,>=21.2 in /usr/local/lib/python3.7/dist-packages (from requests-cache~=0.7.0->chembl_webresource_client) (21.4.0)
Requirement already satisfied: itsdangerous>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from requests-cache~=0.7.0->chembl_webresource_client) (2.1.2)
Requirement already satisfied: url-normalize<2.0,>=1.4 in /usr/local/lib/python3.7/dist-packages (from requests-cache~=0.7.0->chembl_webresource_client) (1.4.3)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from url-normalize<2.0,>=1.4->requests-cache~=0.7.0->chembl_webresource_client) (1.15.0)

##Importing Libraries

In [ ]:
import pandas as pd
from chembl_webresource_client.new_client import new_client

##Target Search for Aromatase

In [ ]:
# Searching for aromatase in chembl database
target = new_client.target
target_query = target.search('aromatase')
targets = pd.DataFrame.from_dict(target_query)
targets

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,"[{'xref_id': 'P11511', 'xref_name': None, 'xre...",Homo sapiens,Cytochrome P450 19A1,20.0,False,CHEMBL1978,"[{'accession': 'P11511', 'component_descriptio...",SINGLE PROTEIN,9606
1,"[{'xref_id': 'P22443', 'xref_name': None, 'xre...",Rattus norvegicus,Cytochrome P450 19A1,20.0,False,CHEMBL3859,"[{'accession': 'P22443', 'component_descriptio...",SINGLE PROTEIN,10116

In [ ]:
# picking the aromatase data on Homo Sapiens(Humans)
aromatase_target= targets.target_chembl_id[0]
aromatase_target

'CHEMBL1978'

In [ ]:
# Selecting aromatase data that have IC50 values
activity = new_client.activity
res = activity.filter(target_chembl_id=aromatase_target).filter(standard_type="IC50")

In [ ]:
# loading all the IC50 aromatase data into 'aromatase_df' variable
aromatase_df=pd.DataFrame.from_dict(res)

#Checking our work

In [ ]:
# checking if our code works
aromatase_df.head(3)

,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,bao_format,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,82585,[],CHEMBL666794,Inhibition of Cytochrome P450 19A1,B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Cytochrome P450 19A1,9606,None,None,IC50,uM,UO_0000065,None,7.1
1,None,94540,[],CHEMBL666794,Inhibition of Cytochrome P450 19A1,B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Cytochrome P450 19A1,9606,None,None,IC50,uM,UO_0000065,None,50.0
2,None,112960,[],CHEMBL661700,In vitro inhibition of human Cytochrome P450 19A1,B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Cytochrome P450 19A1,9606,None,None,IC50,uM,UO_0000065,None,0.238

In [ ]:
# checking if we have only IC50 Data in our dataframe
aromatase_df.standard_type.unique()

array(['IC50'], dtype=object)

In [ ]:
# saving the raw data into a csv file
aromatase_df.to_csv('aromatase_data_raw.csv', index=False)

# Handling missing Data

In [ ]:
# Because of the large size of the dataframe the most efficeint way to clean data will be to drop the rows with misssing 'standard value' and 'canonical_smiles'
aromatase_df_clean = aromatase_df[aromatase_df.standard_value.notna()]
aromatase_df_clean = aromatase_df_clean[aromatase_df.canonical_smiles.notna()]
aromatase_df_clean

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  This is separate from the ipykernel package so we can avoid doing imports until

,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,bao_format,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,82585,[],CHEMBL666794,Inhibition of Cytochrome P450 19A1,B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Cytochrome P450 19A1,9606,None,None,IC50,uM,UO_0000065,None,7.1
1,None,94540,[],CHEMBL666794,Inhibition of Cytochrome P450 19A1,B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Cytochrome P450 19A1,9606,None,None,IC50,uM,UO_0000065,None,50.0
2,None,112960,[],CHEMBL661700,In vitro inhibition of human Cytochrome P450 19A1,B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Cytochrome P450 19A1,9606,None,None,IC50,uM,UO_0000065,None,0.238
3,None,116766,[],CHEMBL661700,In vitro inhibition of human Cytochrome P450 19A1,B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Cytochrome P450 19A1,9606,None,None,IC50,uM,UO_0000065,None,0.057
4,None,118017,[],CHEMBL661700,In vitro inhibition of human Cytochrome P450 19A1,B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Cytochrome P450 19A1,9606,None,None,IC50,uM,UO_0000065,None,0.054
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2889,None,22819795,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4716146,Inhibition of recombinant human aromatase incu...,B,None,None,BAO_0000179,BAO_0000357,...,Homo sapiens,Cytochrome P450 19A1,9606,None,None,IC50,nM,None,None,5.24
2890,None,22819796,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4716146,Inhibition of recombinant human aromatase incu...,B,None,None,BAO_0000179,BAO_0000357,...,Homo sapiens,Cytochrome P450 19A1,9606,None,None,IC50,nM,None,None,104.0
2891,None,22819797,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4716146,Inhibition of recombinant human aromatase incu...,B,None,None,BAO_0000179,BAO_0000357,...,Homo sapiens,Cytochrome P450 19A1,9606,None,None,IC50,nM,None,None,17.7
2892,None,22819798,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4716146,Inhibition of recombinant human aromatase incu...,B,None,None,BAO_0000179,BAO_0000357,...,Homo sapiens,Cytochrome P450 19A1,9606,None,None,IC50,nM,None,None,60.4
2893,None,22819799,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4716146,Inhibition of recombinant human aromatase incu...,B,None,None,BAO_0000179,BAO_0000357,...,Homo sapiens,Cytochrome P450 19A1,9606,None,None,IC50,nM,None,None,439.0

# Data pre-processing

In [ ]:
# We are classfying and isolating each datapoint's standard value into 3 classes
# inactice, active, and intermediate
# standad_value > 10000 => "inactive"
# standard_value <= 1000 => "active"
# else => intermediate
bioactivity_class=[]
for i in aromatase_df_clean.standard_value:
  if float(i)>10000:
    bioactivity_class.append("inactive")
  elif float(i) <=1000:
    bioactivity_class.append("active")
  else:
    bioactivity_class.append("intermediate")

In [ ]:
#Isolating the mol_id of each data point
mol_cid=[]
for i in aromatase_df_clean.molecule_chembl_id:
  mol_cid.append(i)

In [ ]:
#Isolating the canonical_smiles of each data point
canonical_smiles = []
for i in aromatase_df_clean.canonical_smiles:
  canonical_smiles.append(i)

In [ ]:
#Isolating the standard_value of each data point
standard_value = []
for i in aromatase_df_clean.standard_value:
  standard_value.append(i)

In [ ]:
# combining the vairbale we just isolated into one dataframe
# combining bioactivity_class, mol_cid, cononical_smiles, standard_value
data_tuples = list(zip(mol_cid, canonical_smiles, bioactivity_class, standard_value))
aromatase_currated = pd.DataFrame( data_tuples,  columns=['molecule_chembl_id', 'canonical_smiles', 'bioactivity_class', 'standard_value'])
aromatase_currated

,molecule_chembl_id,canonical_smiles,bioactivity_class,standard_value
0,CHEMBL341591,CC12CCC(O)CC1=CCC1C2CCC2(C)C(CC3CN3)CCC12,intermediate,7100.0
1,CHEMBL2111947,C[C@]12CC[C@H]3[C@@H](CC=C4C[C@@H](O)CC[C@@]43...,inactive,50000.0
2,CHEMBL431859,CCn1c(C(c2ccc(F)cc2)n2ccnc2)c(C)c2cc(Br)ccc21,active,238.0
3,CHEMBL113637,CCn1cc(C(c2ccc(F)cc2)n2ccnc2)c2ccccc21,active,57.0
4,CHEMBL112021,Clc1ccccc1Cn1cc(Cn2ccnc2)c2ccccc21,active,54.0
...,...,...,...,...
2813,CHEMBL4755831,Nc1ccc(C(Cn2ccnc2)=C(c2ccc(O)cc2)c2ccc(O)cc2)cc1,active,5.24
2814,CHEMBL4750835,Nc1ccc(C(Cn2cncn2)=C(c2ccc(O)cc2)c2ccc(O)cc2)cc1,active,104.0
2815,CHEMBL4745681,Nc1ccc(C(Cn2cnnc2)=C(c2ccc(O)cc2)c2ccc(O)cc2)cc1,active,17.7
2816,CHEMBL4778401,Oc1ccc(C(=C(Cn2ccnc2)c2cccc(O)c2)c2ccc(O)cc2)cc1,active,60.4
2817,CHEMBL4761359,Nc1cccc(C(Cn2ccnc2)=C(c2ccc(O)cc2)c2ccc(O)cc2)c1,active,439.0

#Saving Currated Dataframe to CSV File

In [ ]:
aromatase_currated.to_csv('aromatase_currated.csv', index=False)
! ls -l

total 4408
-rw-r--r-- 1 root root  203145 Jul  5 16:00 aromatase_currated.csv
-rw-r--r-- 1 root root 1432391 Jul  5 14:47 aromatase_data.csv
-rw-r--r-- 1 root root 1432391 Jul  5 14:53 aromatase_data_raw.csv
-rw-r--r-- 1 root root 1432391 Jul  5 14:47 bioactivity_data.csv
drwx------ 5 root root    4096 Jul  5 14:47 gdrive
drwxr-xr-x 1 root root    4096 Jun 29 13:44 sample_data